# workflow/Snakefile

# Importing libraries

import os
import sys

# Include rules in /rules

# Include commons rule (needed for working workflow)

include: "rules/commons.smk"

# Import modules

include: "rules/admixture.smk"
include: "rules/ahmm.smk"
include: "rules/bcftools.smk"
include: "rules/demesdraw.smk"
include: "rules/dsuite.smk"

# Loading configfile

configfile: "config/config.yaml"

rule all:
    input:
        # rules.fastq_stats.output
    conda:
        "envs/dsuite.yaml"
    default_target: True
