# workflow/Snakefile

# Importing libraries

import os
import sys

# Include rules in /rules

# Include commons rule (needed for working workflow)

include: "rules/commons.smk"

# Loading configfile

configfile: "config/config.yaml"

rule all:
    input:
        # rules.fastq_stats.output
    conda:
        "envs/admixture.yaml"
    default_target: True
