# workflow/Snakefile

# Importing libraries

import os
import sys

# Include rules in /rules

# Include commons rule (needed for working workflow)

include: "rules/commons.smk"

# Import modules

include: "rules/admixture.smk"
include: "rules/ahmm.smk"
include: "rules/bcftools.smk"
include: "rules/demesdraw.smk"
include: "rules/dsuite.smk"
include: "rules/fastq_tools.smk"
include: "rules/genomics_general.smk"
include: "rules/utils.smk"
include: "rules/astral.smk"
include: "rules/newick_utils.smk"

# Loading configfile

configfile: "config/config.yaml"

rule all:
    input:
        # rules.fastq_stats.output
    conda:
        "envs/genomics_general.yaml"
    default_target: True
