#!/usr/bin/env Rscript

suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(ggplot2))

option_list <- list(
  make_option(c("-i", "--input"), type = "character", default = NULL, 
              help = "Path to the input TSV file generated by phlash", metavar = "file"),
  make_option(c("-o", "--output"), type = "character", default = "phlash_plot.png", 
              help = "Name/Path of the output PNG file [default = %default]", metavar = "file"),
  make_option(c("-g", "--generation_time"), type = "numeric", default = 1.0, 
              help = "Generation time in years to scale the X-axis [default = %default]", metavar = "number"),
  make_option(c("-s", "--start_generations"), type = "numeric", default = 0, 
              help = "Lower bound in generations to filter out recent time intervals [default = %default]", metavar = "number")
)

opt_parser <- OptionParser(option_list = option_list)
args <- parse_args(opt_parser)

if (is.null(args$input)) {
  print_help(opt_parser)
  stop("Error: Input file (-i/--input) is required.", call. = FALSE)
}

df <- read.delim(args$input, header = TRUE, check.names = FALSE)

valid_rows <- df[[1]] >= args$start_generations

if (!any(valid_rows)) {
  stop("Error: No data points left after applying the generation filter (-s). Check your threshold.", call. = FALSE)
}

filtered_df <- df[valid_rows, , drop = FALSE]

times_years <- filtered_df[[1]] * args$generation_time
mcmc_samples <- filtered_df[, -1, drop = FALSE]

Ne_median <- apply(mcmc_samples, 1, median)
Ne_low    <- apply(mcmc_samples, 1, quantile, probs = 0.05)
Ne_high   <- apply(mcmc_samples, 1, quantile, probs = 0.95)

plot_data <- data.frame(
  Time = times_years,
  Ne_median = Ne_median,
  Ne_low = Ne_low,
  Ne_high = Ne_high
)

p <- ggplot(plot_data, aes(x = Time)) +
  geom_ribbon(aes(ymin = Ne_low, ymax = Ne_high), fill = "#3182bd", alpha = 0.3) +
  geom_line(aes(y = Ne_median), color = "#08519c", linewidth = 1.2) +
  scale_x_log10(labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  scale_y_log10(labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  labs(
    x = ifelse(args$generation_time == 1, "Time (Generations)", "Time (Years)"),
    y = expression(Effective ~ Population ~ Size ~ (N[e])),
    title = "Effective Population Size (Ne)"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "gray30")
  )

ggsave(args$output, plot = p, width = 8, height = 6, dpi = 300)
